=== ColinEOL/gni/public/schemas/gni_data.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema 
    targetNamespace="http://betula.mbl.edu/GNIData/0.1" 
    xmlns="http://betula.mbl.edu/GNIData/0.1" 
    xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    elementFormDefault="qualified">

  <xs:element name="dataroot" type="datarootType"/>
  <xs:complexType name="datarootType" mixed="false">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" name="record" type="recordType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="recordType" mixed="false">
    <xs:annotation>
      <xs:documentation>Contains raw taxon name and its access point defined either by uri or identifier.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="raw_taxon_name"/>
      <xs:element minOccurs="0" name="uri"/>
      <xs:element minOccurs="0" name="identifier"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:element name="raw_taxon_name" type="xs:string">
    <xs:annotation>
      <xs:documentation>
        Full scientific name of a taxon (Species, Genus, Family, Kingdometc.)
        In case if you have multiple access points, please specify one which contains uri entries to all of them.
      </xs:documentation>
    </xs:annotation>
  </xs:element>
  
  <xs:element name="uri" type="xs:anyURI">
    <xs:annotation>
        <xs:documentation>The URI of an access point of the name information.</xs:documentation>
    </xs:annotation>
  </xs:element>

  <xs:element name="identifier" type="xs:string">
    <xs:annotation>
      <xs:documentation>
        Unique data source identifier of the record (often id of from the database).
        Identifier is used to be included into datasource uri templates.
      </xs:documentation>
    </xs:annotation>
  </xs:element>

</xs:schema>

=== ColinEOL/gni/files/index_fungorum_short.xml
<?xml version="1.0" encoding="utf-8"?>
<dataroot xmlns="http://betula.mbl.edu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://betula.mbl.edu http://betula.mbl.edu/gni_data.xsd">
  <record>
    <raw_taxon_name>Stagonospora octomera Alcalde 1948</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306392</uri>
  </record>
  <record>
    <raw_taxon_name>Stagonospora phragmiticola Hansf. 1945</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306393</uri>
  </record>
  <record>
    <raw_taxon_name>Stagonospora polyspora M.T. Lucas &amp; Sousa da Câmara 1952</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306394</uri>
  </record>
  <record>
    <raw_taxon_name>Stagonospora procerula Petr. 1950</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306395</uri>
  </record>
  <record>
    <raw_taxon_name>Stagonospora querci Sawada 1958</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306396</uri>
  </record>
  <record>
    <raw_taxon_name>Stagonospora rosarum Bat. &amp; Silva{?} 1951</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306397</uri>
  </record>
  <record>
    <raw_taxon_name>Agaricus pileolarius Bull. 1789</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306398</uri>
  </record>
  <record>
    <raw_taxon_name>Stagonospora sacchari T.T. Lo &amp; L. Ling 1950</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306399</uri>
  </record>
  <record>
    <raw_taxon_name>Stemphylium iranicum Esfand. 1950</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306442</uri>
  </record>
  <record>
    <raw_taxon_name>Stemphylium maritimum T.W. Johnson 1957</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306443</uri>
  </record>
  <record>
    <raw_taxon_name>Stemphylium melanopus (Schwein.) S. Hughes 1958</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306444</uri>
  </record>
  <record>
    <raw_taxon_name>Stemphylium trifolii J.H. Graham 1957</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306445</uri>
  </record>
  <record>
    <raw_taxon_name>Stephanospora penangensis Corner &amp; Hawker 1953</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306446</uri>
  </record>
  <record>
    <raw_taxon_name>Arthonia subastroidea subsp. orbilliferum Almq.</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306447</uri>
  </record>
  <record>
    <raw_taxon_name>Arthonia subastroidea subsp. subastroidea Anzi 1864</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306448</uri>
  </record>
  <record>
    <raw_taxon_name>Astrosporina infida</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306449</uri>
  </record>
  <record>
    <raw_taxon_name>Camarosporium tamaricis (Cooke) Grove 1937</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306467</uri>
  </record>
  <record>
    <raw_taxon_name>Stictospora oleae (De Not.) Cif. 1957</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306468</uri>
  </record>
  <record>
    <raw_taxon_name>Stigmatea byrsonimae Bat. &amp; Gayão 1953</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306469</uri>
  </record>
  <record>
    <raw_taxon_name>Stigmatea cremasporae Hansf. 1945</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306470</uri>
  </record>
  <record>
    <raw_taxon_name>Diaporthe sarothamni var. genistae Rehm</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306471</uri>
  </record>
  <record>
    <raw_taxon_name>Stigmatea lomatiae Hansf. 1954</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306472</uri>
  </record>
  <record>
    <raw_taxon_name>Stigmatodothis caseariae Bat. &amp; C.A.A. Costa 1957</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306473</uri>
  </record>
  <record>
    <raw_taxon_name>Stigmatodothis fici-nipponicae I. Hino &amp; Katum. 1958</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306474</uri>
  </record>
  <record>
    <raw_taxon_name>Stigmatodothis sasae (Hara) I. Hino &amp; Katum. 1958</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306475</uri>
  </record>
  <record>
    <raw_taxon_name>Stigmina phaeocarpa (Mitter) M.B. Ellis 1959</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306498</uri>
  </record>
  <record>
    <raw_taxon_name>Stigmina phyllanthi M.B. Ellis 1959</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306499</uri>
  </record>
  <record>
    <raw_taxon_name>Stigmina piliostigmatis M.B. Ellis 1959</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306500</uri>
  </record>
  <record>
    <raw_taxon_name>Gregorella humida (Kullh.) Lumbsch 2005</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306501</uri>
  </record>
  <record>
    <raw_taxon_name>Stigmina pulvinata (Kunze) M.B. Ellis 1959</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306502</uri>
  </record>
  <record>
    <raw_taxon_name>Stigmina pulviniformis (Syd.) S. Hughes 1952</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306503</uri>
  </record>
  <record>
    <raw_taxon_name>Stigmina pusilla (P. Karst.) S. Hughes 1958</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306504</uri>
  </record>
  <record>
    <raw_taxon_name>Strasseria vincae M.T. Lucas &amp; Sousa da Câmara 1954</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306535</uri>
  </record>
  <record>
    <raw_taxon_name>Strattonia tetraspora (R. Stratton) Cif. 1954</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306536</uri>
  </record>
  <record>
    <raw_taxon_name>Herteliana gagei (Sm.) J.R. Laundon 2005</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306537</uri>
  </record>
  <record>
    <raw_taxon_name>Leptonia griseorubella</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306538</uri>
  </record>
  <record>
    <raw_taxon_name>Leptoporus kymatodes</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306539</uri>
  </record>
  <record>
    <raw_taxon_name>Mollisia graminis P. Karst. 1871</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306540</uri>
  </record>
  <record>
    <raw_taxon_name>Nolanea mammosa</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306541</uri>
  </record>
  <record>
    <raw_taxon_name>Nolanea mammosa</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306542</uri>
  </record>
  <record>
    <raw_taxon_name>Phaeographis inusta var. macularis (Leight.) A.L. Sm. 1861</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306543</uri>
  </record>
  <record>
    <raw_taxon_name>Physarum nutans subsp. leucophaeum (Fr.) G. Lister 1911</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306544</uri>
  </record>
  <record>
    <raw_taxon_name>Syndiplodia hypoxyloidea (Cooke) Zambett. 1955</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306685</uri>
  </record>
  <record>
    <raw_taxon_name>Syndiplodia loculata (Mont.) Zambett. 1955</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306686</uri>
  </record>
  <record>
    <raw_taxon_name>Syndiplodia robiniae (Dearn. &amp; Barthol.) Zambett. 1955</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306687</uri>
  </record>
  <record>
    <raw_taxon_name>Synnemadiplodia fiorii (Bacc.) Zambett. 1955</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306688</uri>
  </record>
  <record>
    <raw_taxon_name>Synnemadiplodia marantae (Speg.) Zambett. 1955</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306689</uri>
  </record>
  <record>
    <raw_taxon_name>Synnemadiplodia morina (Syd. &amp; P. Syd.) Zambett. 1955</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306690</uri>
  </record>
  <record>
    <raw_taxon_name>Russula roseicolor J. Blum</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306691</uri>
  </record>
  <record>
    <raw_taxon_name>Synostomella nervicola Petr. 1950</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306692</uri>
  </record>
  <record>
    <raw_taxon_name>Synsporium furcatum Losa 1954</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306693</uri>
  </record>
  <record>
    <raw_taxon_name>Systremma globulosa (Cooke &amp; Massee) Hansf. 1956</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306694</uri>
  </record>
  <record>
    <raw_taxon_name>Systremma sambuci (Pers.) Munk 1957</raw_taxon_name>
    <uri>http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=306695</uri>
  </record>
  <record>
